export const spamKeywords = [
	// Cannabis/weed related
	'weed delivery',
	'cannabis',
	'marijuana',
	'dispensary',
	'thc',
	'cbd',
	'smoakland',
	// Betting/gambling/casino
	'بت 303',
	'bet303',
	'betting',
	'casino',
	'gambling',
	'gclub',
	'online casino',
	'baccarat',
	'roulette',
	'togel',
	'alexistogel',
	'wazamba',
	'sportaza',
	'gclub',
	'atm placement',
	'gclubpro',
	'lyrabet',
	'diuwin',
	// Adult/escort services
	'escort',
	'escorts',
	'models escorts',
	'call girls',
	'adult services',
	'massage parlor',
	// Pharmaceutical spam
	'kamagra',
	'viagra',
	'cenforce',
	'cialis',
	'buy pills',
	'test strips',
	// Adult content
	'influencers gone wild',
	'baddie hub',
	'noodle magazine',
	'avtube',
	// Crypto/financial
	'crypto',
	'cryptocurrency',
	'bitcoin',
	'ethereum',
	'trading',
	'forex',
	'investment',
	'blockchain',
	'nft',
	'defi',
	'coinbase',
	'binance',
	'crypto trading',
	'day trading',
	// Dental/medical
	'dental',
	'dentist',
	'teeth cleaning',
	'root canal',
	'dental implants',
	'orthodontics',
	'braces',
	'invisalign',
	'teeth whitening',
	'oral surgery',
	'periodontal',
	'endodontics',
	'dental clinic',
	'family dentistry',
	'cosmetic dentistry',
	'emergency dental',
	// Industrial/automotive/mechanical
	'pump',
	'lift',
	'truck',
	'trailer',
	'skid',
	'fluid handling',
	'fleet maintenance',
	'industrial applications',
	'equipment',
	'lubrication',
	'lube truck',
	'lube trailer',
	'hydraulic',
	'pneumatic',
	'compressor',
	'generator',
	'machinery',
	'fabrication',
	'welding',
	'machining',
	'custom equipment',
	'industrial equipment',
	'heavy equipment',
	'crane',
	'forklift',
	'excavator',
	'bulldozer',
	'loader',
	'dump truck',
	'semi truck',
	'automotive repair',
	'auto shop',
	'mechanic',
	'transmission',
	'engine repair',
	'brake repair',
	'oil change',
	'tire service',
	'alignment',
	'suspension',
	// Business/services (common spam patterns)
	'web hosting',
	'dedicated server',
	'data center',
	'colocation',
	'hosting provider',
	'car detailing',
	'loft conversion',
	'home renovation',
	'blinds',
	'window',
	'tallow balm',
	'skincare products',
	'coworking space',
	'digital marketing',
	'e-commerce',
	// Professional services spam - greatly expanded
	'lawyer',
	'attorney',
	'legal services',
	'criminal defense',
	'body corporate management',
	'law firm',
	'solar installation',
	'solar panels',
	'uprise solar',
	'electric bills',
	'cleaning services',
	'plumbing',
	'hvac',
	'remodeling',
	'security services',
	'security guards',
	'taxi',
	'airport transfers',
	'luxury transfers',
	'bus rental',
	'laser tattoo removal',
	'laser hair removal',
	'botox',
	'dermal fillers',
	'aesthetic treatments',
	'numbing cream',
	'tattoo',
	'clinic',
	'medical',
	'training course',
	'certification',
	'yoga teacher training',
	'online course',
	'get certified',
	'placement assistance',
	'atm placement',
	'anti-skimming',
	'fraud protection',
	'financial services',
	// New from examples
	'pest control',
	'apartment locators',
	'stem cell therapy',
	'auto repair',
	'european auto',
	'eye care',
	'cosmetic surgeon',
	'endodontics',
	'dentures',
	'window squad',
	'construction',
	'foodservice limited',
	'wreckers',
	'tour packages',
	'travel',
	'enterprises',
	'concierge',
	'weddings',
	'barn repair',
	'lawn mowing',
	'estate agents',
	'residential',
	'digital',
	// New professional services from examples
	'chiropractic',
	'chiropractor',
	'dental',
	'teeth implants',
	'roofing',
	'handyman',
	'pressure washing',
	'auto locksmith',
	'locksmith',
	'garage door',
	'carpet cleaning',
	'junk removal',
	'body corporate',
	'property management',
	'real estate',
	'mortgage broker',
	'insurance',
	'business consultant',
	'accounting',
	'tax preparation',
	'home builder',
	'custom home',
	'concrete',
	'fencing',
	'landscaping',
	'tree service',
	'pest control',
	'appliance repair',
	'heating and air',
	'air conditioning',
	'furnace',
	'duct cleaning',
	'water damage',
	'mold removal',
	'restoration',
	'construction',
	'contractor',
	'flooring',
	'tile',
	'hardwood',
	'carpet installation',
	'painting',
	'drywall',
	'electrical',
	'electrician',
	'generator',
	'panel upgrade',
	'outlet installation',
	'garage door repair',
	'gate repair',
	'deck repair',
	'patio',
	'pergola',
	'gazebo',
	'swimming pool',
	'pool maintenance',
	'spa',
	'hot tub',
	'pool cleaning',
	'window cleaning',
	'gutter cleaning',
	'power washing',
	'exterior cleaning',
	'moving company',
	'storage',
	'self storage',
	'warehouse',
	'logistics',
	'personal injury',
	'slip and fall',
	'car accident',
	'workers compensation',
	'divorce attorney',
	'family law',
	'estate planning',
	'probate',
	'bankruptcy',
	'immigration lawyer',
	'dui attorney',
	'traffic ticket',
	'criminal lawyer',
	'liposuction',
	'cosmetic surgery',
	'plastic surgery',
	'facelift',
	'breast augmentation',
	'rhinoplasty',
	'tummy tuck',
	'coolsculpting',
	'laser treatment',
	'microneedling',
	'dental implants',
	'teeth whitening',
	'invisalign',
	'braces',
	'oral surgery',
	'massage therapy',
	'physical therapy',
	'acupuncture',
	'mental health',
	'counseling',
	// Generic business terms that appear frequently in spam
	'llc',
	'inc',
	'company',
	'business',
	'provider',
	'professional',
	'quality',
	'specialists',
	'services',
	'expert',
	'expertise',
	'years of experience',
	'residential and commercial',
	'top-quality',
	'premium',
	'specialized',
	'tailored solutions',
	'industry experience',
	'we offer',
	'we provide',
	'we specialize',
	'contact us',
	'enquire now',
	'book online',
	'licensed and insured',
	'free estimate',
	'satisfaction guaranteed',
	'family owned',
	'locally owned',
	'established',
	'trusted',
	'reliable',
	'affordable',
	'competitive pricing'
]

export const spamDomains = [
	'fremont',
	'oregon city',
	'noida',
	'chicago',
	'hong kong',
	'taiwan',
	'gold coast',
	'sunshine coast',
	'minneapolis',
	'sacramento',
	'el paso',
	'thailand',
	'melbourne',
	'sydney',
	'brisbane',
	'perth',
	'adelaide',
	'canberra',
	'london',
	'manchester',
	'birmingham',
	'liverpool',
	'glasgow',
	'edinburgh',
	'dublin',
	'belfast',
	'toronto',
	'vancouver',
	'montreal',
	'calgary',
	'ottawa',
	'winnipeg',
	'singapore',
	'kuala lumpur',
	'bangkok',
	'manila',
	'jakarta',
	'hanoi',
	'mumbai',
	'delhi',
	'bangalore',
	'hyderabad',
	'pune',
	'kolkata',
	'dubai',
	'abu dhabi',
	'doha',
	'riyadh',
	'jeddah',
	'kuwait',
	'north lakes',
	'sunshine coast',
	'gold coast',
	'queensland',
	'qld',
	'washington',
	'washington dc',
	'dc'
]

export const businessPartners = [
	// Common business naming patterns
	/\b\w+\s+(llc|inc|corp|ltd|company|services|solutions|group|enterprises|pty ltd)\b/i,
	// Business name with "and" (like "Taylor Pump and Lift")
	/\b\w+\s+(and|&)\s+\w+/i,
	// "Located at" or "specializes in" patterns
	/\b(located at|specializes in|located in|based in|serves|serving)\b/i,
	// Phone/contact patterns
	/\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b/,
	/\b\(\d{3}\)\s*\d{3}[-.\s]?\d{4}\b/, // (704) 786-9400 format
	/\b\d{10,11}\b/, // 10-11 digit phone numbers
	// Email patterns
	/\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b/,
	// Website patterns
	/\b(www\.|http|https|\.com|\.org|\.net|\.au|\.uk|\.ca)\b/i,
	// Business address patterns
	/\b\d+\s+[a-zA-Z\s]+(street|st|avenue|ave|road|rd|boulevard|blvd|drive|dr|lane|ln|way|place|pl|court|ct|circle|cir|drive|dr)\b/i,
	// More specific address patterns (like "4320 Motorsports Dr SW")
	/\b\d+\s+[a-zA-Z\s]+(dr|drive|st|street|ave|avenue|rd|road)\s+(sw|se|nw|ne|north|south|east|west)\b/i,
	// Address with city, state format (like "1140 3rd St NE, Washington, DC")
	/\b\d+\s+[a-zA-Z0-9\s]+(st|street|ave|avenue|rd|road|dr|drive),\s+[a-zA-Z\s]+,\s+[A-Z]{2}\s+\d{5}\b/i,
	// Professional credentials
	/\b(certified|licensed|accredited|registered|qualified|experienced|professional)\b/i,
	// Service area patterns
	/\b(serving|coverage|area|region|county|state|nationwide|local)\b/i,
	// Business operation patterns
	/\b(visit our website|contact us at|call us|designed for|help keep)\b/i
]

export const suspiciousPhrases = [
	'years of experience',
	'top-quality',
	'professional service',
	'residential and commercial',
	'contact us today',
	'call now',
	'book online',
	'get quote',
	'free consultation',
	'licensed and insured',
	'fully licensed',
	'certified professionals',
	'expert team',
	'tailored to meet',
	'unique needs',
	'exceptional service',
	'customer satisfaction',
	'state-of-the-art',
	'cutting-edge',
	'industry-leading',
	'award-winning',
	'family owned',
	'locally owned',
	'established since',
	'trusted by',
	'reliable service',
	'satisfaction guaranteed',
	'free estimate',
	'competitive pricing',
	'affordable rates',
	'same day service',
	'24/7 service',
	'24 hour service',
	'emergency service',
	'fully bonded',
	'fully insured',
	'background checked',
	'drug tested',
	'we pride ourselves',
	'we are committed',
	'we are dedicated',
	'our mission',
	'premier choice',
	'leading provider',
	'top choice',
	'best in class',
	'comprehensive solutions',
	'full service',
	'turn-key solutions',
	'one-stop shop',
	'fast and efficient',
	'prompt service',
	'quick response',
	'timely delivery',
	'peace of mind',
	'stress-free',
	'hassle-free',
	'worry-free',
	'custom solutions',
	'personalized service',
	'individual attention',
	'client-focused',
	'save hundreds of dollars',
	'potentially save',
	'find out how much you could save',
	'get started below',
	'customers can',
	'save per year',
	'on their electric bills',
	// New phrases from the Taylor Pump example and similar
	'expert craftsmanship',
	'reliable service',
	'contact us at',
	'visit our website',
	'specializes in',
	'designed for',
	'help keep',
	'running efficiently',
	'find the right',
	'for your needs',
	'located at',
	'custom designed',
	'fleet maintenance',
	'industrial applications',
	'handling systems'
]
